### ISSUE TITLE
add link to github repo

### ISSUE THREAD

**Issue by mikelmaron** [state-hiu/osmgeoweek-2016#28]
in footer and other appropriate places. so folks can help directly if they want

**Comment by d3netxer** [comment]
adding a link to the bottom of the page for now

**Comment by harry-wood** [comment]
Think you can close this. That link seems fine.

As a related aside though, anyone know the github repo for http://osmstories.org ?

**Comment by mikelmaron** [comment]
@harry-wood https://github.com/osmlab/basket
